# permissions for end users to edit helmopsovereasies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmopsovereasy-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - helmopsovereasies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - helmopsovereasies/status
  verbs:
  - get
