# permissions for end users to view helmopsovereasies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmopsovereasy-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - helmopsovereasies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - helmopsovereasies/status
  verbs:
  - get
