apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 15; echo "hello world"
    image: busybox
    name: busybox
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo 'Hello from the postStart handler'"]
      preStop:
        exec:
          command: ["/bin/sh","-c","echo 'Hello from the preStop handler'"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
