# permissions for end users to edit ansibleopsovereasies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansibleopsovereasy-editor-role
rules:
- apiGroups:
  - ansible-operators-over-ez.mydomain.com
  resources:
  - ansibleopsovereasies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ansible-operators-over-ez.mydomain.com
  resources:
  - ansibleopsovereasies/status
  verbs:
  - get
